config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
	/**
	 * Here, we are connecting '/' (base path) to a controller called 'Pages',
	 * its action called 'display', and we pass a param to select the view file
	 * to use (in this case, src/Template/Pages/home.ctp)...
	 */
	$routes->connect('/contact', ['controller' => 'pages', 'display', 'contact']);
	//$routes->connect('/login', ['controller' => 'users', 'display']);
	//$routes->connect('/login', ['controller' => 'users', 'action' => 'display', 'add']);
	//$routes->connect('/logout', ['controller' => 'users', 'logout']);
	$routes->connect('/login', ['controller' => 'users', 'display', 'login']);
	$routes->connect('/about', ['controller' => 'pages', 'display', 'about']);
	$routes->connect('/annonces', ['controller' => 'annonces', 'action' => 'index']);
	$routes->connect('/', ['controller' => 'pages', 'display', 'about']);
	$routes->connect('/login', ['controller' => 'users', 'display']);

	//$routes->connect('/annonces', ['controller' => 'annonces', 'display', 'annonces']);

	/**
	 * Connect catchall routes for all controllers.
	 *
	 * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
	 *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
	 *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
	 *
	 * Any route class can be used with this method, such as:
	 * - DashedRoute
	 * - InflectedRoute
	 * - Route
	 * - Or your own route class
	 *
	 * You can remove these routes once you've connected the
	 * routes you want in your application.
	 */
	$routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Annonce.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Annonce Entity.
 *
 * @property int $id_annonce
 * @property int $id_annonceur
 * @property string $stage_title
 * @property string $stage_description
 * @property int $program_id
 * @property \App\Model\Entity\Programme $programme
 * @property \Cake\I18n\Time $start_date_stage
 * @property \Cake\I18n\Time $end_date_stage
 * @property bool $compensation
 * @property int $idTags
 * @property bool $bool_college
 * @property int $job_title
 * @property \Cake\I18n\Time $date_publication
 */
class Annonce extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id_annonce' => false,
    ];
}

src/Model/Table/AnnoncesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Annonce;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Annonces Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Programmes
 */
class AnnoncesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('annonces');
        $this->displayField('id_annonce');
        $this->primaryKey('id_annonce');

        $this->belongsTo('Programs', [
            'foreignKey' => 'program_id',
            'joinType' => 'INNER'
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'id_annonceur',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id_annonce')
            ->allowEmpty('id_annonce', 'create');

        $validator
            ->integer('id_annonceur')
            ->requirePresence('id_annonceur', 'create')
            ->notEmpty('id_annonceur');

        $validator
            ->requirePresence('stage_title', 'create')
            ->notEmpty('stage_title');

        $validator
            ->requirePresence('stage_description', 'create')
            ->notEmpty('stage_description');

        $validator
            ->date('start_date_stage')
            ->requirePresence('start_date_stage', 'create')
            ->notEmpty('start_date_stage');

        $validator
            ->date('end_date_stage')
            ->requirePresence('end_date_stage', 'create')
            ->notEmpty('end_date_stage');

        $validator
            ->boolean('compensation')
            ->requirePresence('compensation', 'create')
            ->notEmpty('compensation');

        $validator
            ->boolean('bool_college')
            ->allowEmpty('bool_college');

        $validator
            ->allowEmpty('job_title');

        $validator
            ->date('date_publication')
            ->requirePresence('date_publication', 'create')
            ->notEmpty('date_publication');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['program_id'], 'Programs'));
        return $rules;
    }
}

src/Controller/AnnoncesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;
use Cake\Event\Event;

/**
 * Annonces Controller
 *
 * @property \App\Model\Table\AnnoncesTable $Annonces
 */
class AnnoncesController extends AppController
{

    public function beforeFilter(Event $event)
    {
        $creerAnnonceURL = array(
            'controller' => 'Annonces',
            'action' => 'display',
            'creerAnnonce'
        );
        $this->Auth->allow(['annonces', 'view']);
        $this->set('creerAnnonceURL', $creerAnnonceURL);
        $this->set('user', $this->request->session()->read('Auth.User'));

    }

    public function index()
    {
        $this->set('annonces', $this->Annonces->find('all'));
    }

    public function annoncesUser()
    {
        $uid = $this->Auth->user('user_id');
        $this->set('annonces', $this->Annonces->find('all')->where(['Annonces.id_annonceur' => $uid])->contain(['Users'])->contain(['Programs']));
        // $query->where(['Annonces.id_annonceur' => $uid]);
        //$this->set(compact('annonces'));
    }

    public function annonces()
    {
        $this->set('array_received', $this->request->session()->read('arrayIds'));
        if (is_null($this->request->session()->read('arrayIds'))) {
            $this->log('NOOOOOOOOO', 'debug');
            $this->set('annonces', $this->Annonces->find('all', array('order' => array('date_publication' => 'asc')))->contain(['Users'])->contain(['Programs']));
            $this->set(compact('annonces'));
        } else {
            $this->log('ici', 'debug');
            $this->set('annonces', $this->Annonces->find('all', array('order' => array('date_publication' => 'asc')))->contain(['Users'])->contain(['Programs'])->where(['program_id IN' => $this->request->session()->read('arrayIds')]));
            $this->set(compact('annonces'));
            $this->request->session()->delete('arrayIds');
        }

        // $nombreAnnonces = sizeof($annonces);
    }

    public function view($id = null)
    {
        $annonce = $this->Annonces->get($id, [
            'contain' => ['Users']
        ]);
        $this->set(compact('annonce'));
    }

    public function isAuthorized($user)
    {

        // Par défaut refuser
        return true;
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {

        $this->setUpDropdowns();

        $annonce = $this->Annonces->newEntity();

        if ($this->request->session()->read('Auth.User.user_type') === 'etudiant') {
            $annonce['type_annonce'] = 0;
            $this->loadModel('Students');
            $info = $this->Students->find('all')->where(['user_id' => $this->request->session()->read('Auth.User.user_id')])->first();
            $this->set('info', $info);
        } else {
            $annonce['type_annonce'] = 1;
        }

        if ($this->request->is('post')) {
            $annonce = $this->Annonces->patchEntity($annonce, $this->request->data);
            $annonce->id_annonceur = $this->request->session()->read('Auth.User.user_id');
            $annonce->date_publication = date("y-m-d");
            if ($this->request->session()->read('Auth.User.user_type') === 'etudiant') {
                $annonce['program_id'] = $info->program_id;
            } else {
                $annonce['program_id'] = $annonce['program_id'] + 1;
            }
            if ($this->Annonces->save($annonce)) {
                $this->Flash->success(__('Annonce enregistrée'));
                return $this->redirect(['action' => 'annonces']);
            } else {
                $this->Flash->error(__('Une erreure est survenue lors de la sauvegarde cette de l\'annonce.'));
            }
        }
        $this->set(compact('annonce', 'users'));
        $this->set('_serialize', ['annonce']);
    }

    private function setUpDropdowns()
    {
        $programs = $this->getPrograms();
        $formatedPrograms = $this->formatDropdownPrograms($programs);

        $this->set('programs', $formatedPrograms);
    }

    public function getPrograms()
    {
        $conn = ConnectionManager::get('default');
        $querry = $conn->prepare(
            'SELECT * FROM `programs` ORDER BY `programs`.`id_program` ASC'
        );
        $querry->execute();
        $liste = array();

        do {
            $progs = $querry->fetch('assoc');
            array_push($liste, $progs);
        } while ($progs);

        return $liste;
    }

    public function formatDropdownPrograms($liste)
    {

        $formatedList = array();
        $cmp = 0;
        foreach ($liste as $ele) {
            if ($ele) {
                array_push($formatedList, ($ele['id_program']));
                $formatedList[$cmp] = $ele['program_name'];
                $cmp++;
            }
        }
        return $formatedList;
    }

    /**
     * Edit method
     *
     * @param string|null $id Annonce id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $annonce = $this->Annonces->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $annonce = $this->Annonces->patchEntity($annonce, $this->request->data);
            if ($this->Annonces->save($annonce)) {
                $this->Flash->success(__('Annonce sauvegargée'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('Une erreure est survenue lors de l\'édition cette de l\'annonce.'));
            }
        }
        $programmes = $this->Annonces->Programmes->find('list', ['limit' => 200]);
        $this->set(compact('annonce', 'programmes'));
        $this->set('_serialize', ['annonce']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Annonce id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id)
    {
        $this->request->allowMethod(['post', 'delete']);
        $annonce = $this->Annonces->get($id);
        if ($this->Annonces->delete($annonce)) {
            $this->Flash->success(__('Annonce supprimée'));
        } else {
            $this->Flash->error(__('Une erreure est survenue lors de la supression de l\'annonce.'));
        }
        return $this->redirect(['action' => 'annonces']);
    }

    public function sendMessage($id_destinataire = null, $messageTitle = null)
    {
        $messageController = new MessagesController();

        $message = $messageController->Messages->newEntity();
        $message = $messageController->Messages->patchEntity($message, $this->request->data);

        $messageCoprs = $message->message_coprs;
        $messageController->add($messageCoprs, $id_destinataire, $messageTitle);

        $this->redirect(
            ['action' => 'annonces']
        );
    }
}

src/Template/Annonces/add.ctp
<!DOCTYPE html>
<html>
<head>
    <title>
        Internfinder
    </title>
    <?= $this->Html->css('home.css') ?>
    <?= $this->Html->css('contact.css') ?>
    <?= $this->Html->css('annonces.css') ?>
    <?= $this->Html->css('about.css') ?>
    <?= $this->Html->script('addAnnonce.js') ?>
</head>
<body style="background-color: #FFF; color: #000; ">

<div class="col-md-1">
</div>

<div class="col-md-10">
    <?= $this->Form->create($annonce) ?>
    <legend><?= __('Publier une annonce') ?></legend>
<fieldset class="annonce_form">

    <?php
    $this->Form->input('annonce_type', [
        'options' => ['rechercheStage' => 'Recherche de stage', 'rechercheStagiere' => 'Recherche de stagiere'], 'label' => 'Type de lannonce',
        'type' => 'select',
        'class' => 'dropdown',
        'default' => 'Recherche de stage'
    ]);

    echo $this->Form->input('stage_title', ['label' => 'Titre de l\'annonce']);
    echo $this->Form->input('stage_description', ['label' => 'Description']);
    echo $this->Form->input('qualifications_desc', ['label' => 'Qualités requises']);
    echo $this->Form->input('responsabilites_desc', ['label' => 'Responsabilités']);
    ?>

    <br>
    <br>
    <div class="Debutstage"> 
        <?php
        echo '<label id="lblDebutDate">Debut du Stage</label>';
        echo $this->Form->date('start_date_stage',[
            'year' => [
                'class' => 'year-classname',
            ],
            'month' => [
                'class' => 'month-class',
                'data-type' => 'month',
            ]
        ]);
        ?>
    </div>
    <br>
    <br>

    <div class="Finstage">
        <?php
        echo '<label id="lblFinDate">Fin du Stage</label>';
        echo $this->Form->date('end_date_stage', [
            'year' => [
                'class' => 'year-classname',
            ],
            'month' => [
                'class' => 'month-class',
                'data-type' => 'month',
            ],
        ]);
        ?>
    </div>

    <br>
    <br>
    <br>

    <?php
    if($user['user_type'] == 'etudiant') {
        echo  $this->Form->input('job_title', ['label' => 'Nom du poste']);
    }else{

        echo  $this->Form->input('program_id', [
            'options' => $programs,
            'label' => 'Nom du programme',
            'class' => 'dropdown'
        ]);
        $annonce->type_annonce = 0;

    } ?>
    <br>
    <br>
    <?php echo $this->Form->input('compensation', [
        'options' => ['0' => 'Non', '1' => 'Oui'], 'label' => 'Compensation',
        'type' => 'select',
        'class' => 'dropdown',
        'default' => '1'
    ]);
    ?>
<?= $this->Form->button(__('Enregistrer'), ['class' => 'btn btn-primary btn-lg btn-custom addUser']) ?>
<?= $this->Form->end() ?>
</fieldset>

</div>

<div class="col-md-1">
</div>

</body>
</html>

src/Template/Annonces/annonces.ctp
<title>
        Internfinder
    </title>
    <?= $this->Html->css('annonces.css') ?>
    <?= $this->Html->css('about.css') ?>
    <?= $this->Html->script('annonce.js') ?>

    <body>
    <h1 class="title">Annonces actives</h1>
          <div id="publier_annonce">
              <button
                  class="btn btn-primary btn-lg btn-custom new-msg-button"><?= $this->Html->link('Publier',array('controller' => 'annonces', 'action' => 'add'));?></button>
          </div>

          <div class="col-md-12">
<!--               <?php $nb = sizeof($annonces);
                    if($nb == 1) {
                    echo 'Hey';
                    }
                    else {
                    echo 'Hola';
                    echo $nb;
                    }
              ?>

               <?php 
                      if ($nb == 1) {
                        echo 'Il n\'y a pas d\'annonces à afficher !';
                      }
                      else {
                      
                      }
               ?> -->
              <div class="table-responsive annonce_table">
              <table class="table">
              <tr>
                  <th>Titre</th>
                  <th>Auteur</th>
                  <th>Programme</th>
                  <th>Date de publication</th>
                  <th>Compensation</th>
                  <th>Type</th>
              </tr>

              <?php foreach ($annonces as $annonce): ?>
                <tr>
                  <td>
                      <?= $this->Html->Link($annonce->stage_title, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                    <?= $this->Html->Link($annonce->user->fullname, ['controller' => 'users','action' => 'profil', $annonce->user->username]) ?>
                  </td>
                  <td>
                      <?= $this->Html->tag('span', $annonce->program->program_name, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                      <?= $this->Html->tag('span',$annonce->date_publication, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                      <?php 
                        if($annonce->compensation == true) {
                          echo 'Oui';
                        }
                        else {
                          echo 'Non';
                        }
                      ?>
                      <!-- <?= $this->Html->tag('span',$annonce->compensation, ['action' => 'view', $annonce->id_annonce]) ?> -->
                  </td>
                  <td>
                      <?php
                        if($annonce->type_annonce == 1) { 
                          echo '<span class="glyphicon glyphicon-briefcase"></span>';
                        }
                        else if($annonce->type_annonce == 0) {
                          echo '<span class="glyphicon glyphicon-sunglasses"></span>';
                        } 
                      ?>
                  </td>
              </tr>
              <?php endforeach; ?>
          </table>
          </div>
          </div>
          

            
          
  </body>

src/Template/Annonces/annonces_user.ctp
<title>
        Internfinder
    </title>
    <?= $this->Html->css('annonces.css') ?>
    <?= $this->Html->css('about.css') ?>
    <?= $this->Html->script('annonce.js') ?>

    <body>
    <h1 class="title">Mes annonces </h1>
    <div id="publier_annonce">

        <button
            class="btn btn-primary btn-lg btn-custom new-msg-button"><?= $this->Html->link('Publier',array('controller' => 'annonces', 'action' => 'add'));?></button>
            </div>

          <div class="col-md-12">
              <div class="table-responsive annonce_table">
            <table class="table">
              <tr>
                  <th>Titre</th>
                  <th>Programme</th>
                  <th>Date de publication</th>
                  <th>État</th>
                  <th>Type</th>
              </tr>

              <?php foreach ($annonces as $annonce): ?>
                <tr>
                  <td>
                      <?= $this->Html->Link($annonce->stage_title, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                      <?= $this->Html->tag('span', $annonce->program->program_name, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                      <?= $this->Html->tag('span',$annonce->date_publication, ['action' => 'view', $annonce->id_annonce]) ?>
                  </td>
                  <td>
                      Ouvert
                  </td>
                  <td>
                      <?php
                          if($annonce->type_annonce == 1) { 
                            echo '<span class="glyphicon glyphicon-briefcase"></span>';
                          }
                          else if($annonce->type_annonce == 0) {
                            echo '<span class="glyphicon glyphicon-sunglasses"></span>';
                          } 
                        
                      ?>
                  </td>
              </tr>
              <?php endforeach; ?>
          </table>
          </div>
          </div>
          

            
          
  </body>

src/Template/Annonces/view.ctp
<Html>
<head>
	<?= $this->Html->css('annonces.css') ?>
	<?= $this->Html->script('annonce.js') ?>
    <?= $this->Html->css('about.css') ?>
	<?php $messageTitle = "Application à l'offre ".$annonce->stage_title." de la part de : ".$annonce->user->fullname; ?>
</head>
<body class="ls_annonces">
<!-- <div class="col-md-2">
</div> -->
<div class="col-md-12">
	<div class="contenu_page">
	<?php 
	if($this->request->session()->read('Auth.User.user_id') != $annonce->id_annonceur) {
		if($annonce->type_annonce == 1) {
			echo '<a href="#" class="btn btn-primary btn-lg btn-custom postuler" data-toggle="modal" data-target="#uploadModal">Postuler</a>';
		}
		else if($annonce->type_annonce == 0) {
			echo '<a href="#" class="btn btn-primary btn-lg btn-custom postuler" data-toggle="modal" data-target="#confirmEntrevue">Entrevue</a>';
		}
    }
    else if($this->request->session()->read('Auth.User.user_id') == $annonce->id_annonceur){
      	echo $this->Form->postLink('Supprimer', ['action' => 'delete', $annonce->id_annonce], ['class' => 'btn btn-primary btn-lg btn-custom postuler'], ['confirm' => 'Êtes-vous sûr de vouloir supprimer cette annonce ?']) ;

    }	
	?>
	
		<div class="title_annonce">
			<?= h($annonce->stage_title)?> <span>publié par <?= $this->Html->Link($annonce->user->username, ['controller' => 'users', 'action' => 'profil', $annonce->user->username]) ?> </span>
			
			<span class="glyphicon glyphicon-star-empty favorite"></span>
			<span class="added_to_fav">Ajouté au favoris!</span>
			<h5>Période du stage : <?= h($annonce->start_date_stage) ?> au <?= h($annonce->end_date_stage) ?></h5>
			<?php 
                        if($annonce->compensation == true) {
                          echo '<span class="glyphicon glyphicon-usd compens"></span style="color:#4593e3 !important; font-size: 16px;">Possibilité de rémunération</span>';
                        }
                        else {
                          echo '<span class="glyphicon glyphicon-usd no_compens"></span> <span style="color: grey !important; font-size: 16px;">Stage non rémunéré</span>';

                        }
            ?>

			<hr>
		</div>
		<div class="contenu_annonce">
		 	<section>
			 	<h4>Description:</h4> 
				<h5><?= h($annonce->stage_description) ?></h5>
			</section>

			<section>
				<h4>Qualifications:</h4> 
					<?= $annonce->qualifications_desc ?>
			</section>

			<section>
				<h4>Responsabilités:</h4>
				<?= $annonce->responsabilites_desc ?>
			</section>
		</div>
</div>
</div>
<!-- <div class="col-md-2">
</div> -->



<div id="uploadModal" class="login-block modal fade" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" id="btn_close_modal">&times;</button>
				<h4 class="modal-title">Envoyer un message à <?= $annonce->user->username ?></h4>
			</div>
			<div class="modal-body">
				<?php echo $this->Form->create('uploadFile', array( 'type' => 'file'));
				echo $this->Form->input('pdf_path', array('type' => 'file','label' => 'Pdf'));
				echo $this->Form->end();?>
			</div>
			<div class="modal-footer">
			<?= $this->Form->button(__('Envoyer')) ?>
			</div>
		</div>
	</div>
</div>

<div id="confirmEntrevue" class="login-block modal fade" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" id="btn_close_modal">&times;</button>
				<h4 class="modal-title">Envoyer un message à <?= $annonce->user->username ?></h4>
			</div>
			<div class="modal-body">
				Voulez-vous vraiment programmer une entrevue avec <?= $annonce->user->username ?> ?
			</div>
			<div class="modal-footer">
			<?= $this->Form->button('Oui') ?>
			<?= $this->Form->button('Non') ?>
			</div>
		</div>
	</div>
</div>


<div id="messagingModal" class="login-block modal fade" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" id="btn_close_modal">&times;</button>
				<h4 class="modal-title">Envoyer un message à <?= $annonce->user->username ?></h4>
			</div>
			<div class="modal-body">
			<?= $this->Form->create('msg',['url' =>['controller' => 'Annonces', 'action' => 'sendMessage', $annonce->user->user_id, $messageTitle]]) ?>
				    <fieldset>
				        <?php
				            echo $this->Form->input('message_coprs', array('type' => 'textarea'));
				        ?>
				    </fieldset>
				    <?php
					echo $this->Form->Submit(__('Confirmer'));
					?>
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>


</body>
</Html>